# use 'REST Client' VSCode extension for quick testing

POST http://localhost:3000/user/new HTTP/3
X-User-ID: 00001

### (3 #s needed to separate requests)

GET http://localhost:3000/user/00001 HTTP/3
X-User-ID: 00001

###

POST http://localhost:3000/user/new HTTP/3
X-User-ID: 00002

###

GET http://localhost:3000/user/00002 HTTP/3
X-User-ID: 00002