import { Inter } from 'next/font/google'
import { useRouter } from 'next/router';
import { useSession, signIn, signOut } from 'next-auth/react';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/*export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}*/

const Layout = ({ children }) => {
    const router = useRouter();
    const { data, status } = useSession();

    return (
        <div>
            <nav className="flex items-center justify-between p-6 bg-gray-800 text-white">
                <div className="flex items-center space-x-4">
                    <span className="cursor-pointer" onClick={() => router.push('/')}>Home</span>
                    <span className="cursor-pointer" onClick={() => router.push('/charts')}>Charts</span>
                    <span className="cursor-pointer" onClick={() => router.push('/upload')}>Upload Data</span>
                </div>
                <div className="flex items-center space-x-4">
                    {status === 'authenticated' ? (
                        <>
                            <span>Welcome, {data.user.name}</span>
                            <img src={data.user.image} alt={data.user.name + ' photo'} className="h-12 w-12 rounded-full"/>
                            <span className="cursor-pointer" onClick={signOut}>Sign Out</span>
                        </>
                    ) : (
                        <span
                            className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-full cursor-pointer hover:bg-red-700"
                            onClick={() => signIn('google')}
                            >
                          <img src="https://developers.google.com/identity/images/g-logo.png" alt="Google logo"
                               className="w-5 h-5 mr-2 rounded-full"/>
                          Sign In with Google
                        </span>


                    )}
                </div>
            </nav>
            <aside>
                {/* Sidebar content goes here */}
            </aside>
            <main className={inter.className}>{children}</main>
        </div>
    );
};

export default Layout;